### PR TITLE
add functionality to download all the files in a zip file from work s…

### LINKED ISSUE #520: Add batch download capability
## Background or Context 

Add a way to batch download multiple files at once rather than having to download them individually.

### PR DESCRIPTION
**Pull request by blancoj**
Fixes #520 

Workflow:
Step 1: Delete  /tmp/archive_[workID] if it exists
Step 2: Create a new folder /tmp/archive_[workID]
Step 3: Download all the files in /tmp/archive_[workID]
Step 4: Zip all the files in the folder
Step 5: Sends the archive file to the browser.

### CODE REVIEW

**Comment by billdueber** [comment]
This is going to run into the same problem we had before with `/tmp/` filling up. You should dump stuff into (not tested code) `File.join(Rails.root, 'tmp')` as your root.

I have two other concerns:
  * If I'm reading it right, it builds the zip file in memory, which might not be possible
  * You're not cleaning up after yourself; the extracted files hang around.

**Comment by billdueber** [comment]
I'm still nervous about what looks like [each file getting read into memory](https://github.com/mlibrary/umrdr/pull/581/files#diff-a86213c1d15e8d47e57b9bde96df32deR66). Is anyone else?

I think you could just use [IO::copy_stream](https://ruby-doc.org/core-2.3.3/IO.html#method-c-copy_stream) to accomplish the same thing without blowing up the memory.

**Comment by blancoj** [comment]
Yea, I see what you're saying.  Let me look into IO:copy_stream

**Comment by botimer** [comment]
I am nervous about anything that isn't stream-based. It'd be best if we could just stream to the client, but I think we will probably have to write the whole archive to disk. At that point, we should be able to use X-Sendfile to avoid tying up a Ruby process for an entire (likely large) download.

**Comment by skorner** [comment]
Yes, please don't build unbounded arbitrary sized files in memory:) FYI, the heliotrope folks are using X-Sendfile to delivery their dynamic derivatives. From the Apache config:

 `XSendFilePath /hydra/heliotrope-production/current/tmp/derivatives`

**Pull request merged**
