### PR TITLE
Add Draft help text

### LINKED ISSUE #416: Add help text to draft / save on deposit works page
Select draft to save your work without making it public. All non-draft works are publicly viewable after being saved. Select save and add files on the next page. 

screen shot 2016-08-10 at 11 26 55 am

### PR DESCRIPTION
**Pull request by njaffer**
screen shot 2016-08-11 at 9 40 27 am
closes #416

### CODE REVIEW

**Comment by justcolin** [comment]
@njaffer: Can you move the help paragraph to be above the checkbox? Generally help text should precede the field that you are talking about.

**Comment by njaffer** [comment]
@justcolin: The reason it is above Save and below Draft is because it is help text for both Draft and Save. I can move it up also, if that is needed. Thoughts @amyneeser ?

**Comment by justcolin** [comment]
It should be before both them in the HTML so people using some assistive technologies get the help text before they encounter the form element. It also makes things a little clearer for people looking at the page.

**Comment by justcolin** [comment]
It may make more sense to split the save help text out so each bit of help text can be directly above the thing that it is relevant to.

@bnhowell or @heidisb: do you have preferences on whether or not the save and draft help text is all put above these items, or if it is split with the draft help text above the draft checkbox and the save help text above the save checkbox.

**Comment by heidisb** [comment]
What @justcolin said. I recommend a split -- help text directly about the thing it is relevant too. I would also flip the order of the draft help sentences (i.e. state the default, then present the alternative).

All non-draft works are publicly viewable after being saved. Select draft to save your work without making it public.
Checkbox for Draft
Select Save and add files on the next page.
Save button

**Comment by amyneeser** [comment]
+1 to Heidi's suggestions. Thanks!

**Comment by njaffer** [comment]
Done. Thanks all!
screen shot 2016-08-15 at 9 38 12 am

**Comment by heidisb** [comment]
Beautiful. I <3 microcopy. Thanks for implementing the changes @njaffer!

**Comment by justcolin** [comment]
Looks great!

**Pull request merged**
