### PR TITLE
Add browse button

### LINKED ISSUE #388: Add browse functionality
We need a way for users to be able to see what is in the repository. Probably a browse button. Browse options could be the current search facets: discipline, creator, keyword, etc.

### PR DESCRIPTION
**Pull request by njaffer**
closes #388 
screen shot 2016-08-11 at 11 57 05 am

### CODE REVIEW

**Comment by njaffer** [comment]
@justcolin: I put both buttons side by side. @amyneeser suggested putting browse button above deposit button.

**Comment by justcolin** [comment]
@njaffer: Has this been checked at mobile sizes (very narrow window sizes)?

**Comment by njaffer** [comment]
@justcolin: @amyneeser: Would this be better: (both buttons are not in one row)
screen shot 2016-08-12 at 2 23 28 pm

**Comment by justcolin** [comment]
@njaffer: This should be better. Can you add a screenshot taken with a narrow window width (after the content reflows)?

Thanks!

**Comment by njaffer** [comment]
@justcolin: I have added two new line characters between the 2 buttons (which I believe not the best way!). Would you rather use css to align the buttons.

**Comment by justcolin** [comment]
@njaffer: I'll send suggested HTML/CSS later today when I get a chance to properly review it (in some conference sessions currently).

**Comment by amyneeser** [comment]
I like the browse button on top of the deposit button. It looks great!

**Comment by njaffer** [comment]
@justcolin: Let me know if you have some ideas about using css instead of new line chars

**Comment by justcolin** [comment]
@njaffer: If you keep the CSS/HTML that the current production homepage uses all you have to do is add the `<a>` tag for the browse link directly before the `<a>` tag for the deposit link, then make the browse tag for the deposit link `display: block;` and `margin-top: 1em;`.

**Comment by grosscol** [comment]
@justcolin Merging this, so you can put in your fixes.

**Pull request merged**
