### PR TITLE
UMRDR-753 User User.to_params rather than User.user_key in URLs

### PR DESCRIPTION
**Pull request by jimeng**

### CODE REVIEW

**Comment by jimeng** [comment]
The problem being fixed here is in two views and a helper that are in the hyrax gem.  We override the views.  The specs for the views fail without our versions of them and pass with our fixes. Another hyrax partial in the same view invokes a method from a hyrax helper to render a link, and the helper makes the same mistake as in the other two partials, so this PR fixes the problem in the helper.  Again, the specs fail before our fixes are included and succeed when the fixes are included.

**Comment by botimer** [comment]
I'm a little confused about what you mean. Are you saying that there are tests in the gem that verify broken behavior and both the fix and the updated tests are required at the application?

If that is the case, is there an issue/pr for Hyrax?

To be clear about my point: it appeared that we should be able to verify that the helper produces the right values without adding the view-testing infrastructure. If we are only adding it to temporarily override upstream tests, I would like to see a corresponding upstream issue to fix it there, and one here to remove the workarounds brought in.

The general point is that view tests typically require a lot of mocking and maintenance. It just seemed a bit odd that this would be the first occurrence of the need to do any of that in the app, and I'm cautious about the amount of view tests growing.

**Comment by jimeng** [comment]
The problems with the three partials in this view have been fixed in hyrax
master, but it is not known when we will get a gem update that includes
those fixes.  So we are fixing it in umrdr code by overriding two views and
a helper method.  If you would rather we add the fixes without tests, we
could do that.


----
Jim Eng
jimeng@umich.edu
734-645-4123

**Comment by botimer** [comment]
Got it. My suggestion here would be to reference the upstream change (issue/pr) and record an issue for the gem upgrade that mentions that these additional overrides should be removed at that point. Sorry if that exists and I just missed it. Thanks for explaining this change.

**Comment by jimeng** [comment]
Some conflicts could not be resolved when we tried to rebase.

**Pull request closed without merging**
