### PR TITLE
CSS fixes for issue #311

### PR DESCRIPTION
**Pull request by jonearley**
**Before**
screenshot-localhost 3000 2016-04-26 14-22-22

**After**
screenshot-localhost 3000 2016-04-26 14-39-24

### CODE REVIEW

**Comment by amyneeser** [comment]
@jonearley Is there a way to make the username on the left side not break onto multiple lines?

**Comment by jonearley** [comment]
@amyneeser short answer: probably not. Username length and screen size can vary user to user making it difficult to prevent wrapping. We could make the text smaller to help prevent some usernames from wrapping.

In this image I have my browser fairly narrow. If I let the site go full width in my browser it doesn't wrap.

**Comment by grosscol** [comment]
reallylonguniqnamegoodluckwrappingme@umich.edu

**Comment by amyneeser** [comment]
haha fair enough.

**Comment by justcolin** [comment]
@jonearley: The color of the "Go" button in the header is still incorrect. See the production website for the correct colors/states.

Thanks!

**Comment by grosscol** [comment]
@justcolin I'm leaving this one for you to merge when you're okay with it.

**Comment by respinos** [comment]
(Technically, `uniqname@umich.edu` has an upper limit of 18 characters.)

**Comment by grosscol** [comment]
@respinos Thanks. Allow for 18 characters and wrap at "@" might be a decent heuristic.  Pending the dependency update, that could be a neat little issue.

**Comment by justcolin** [comment]
I talked with @jonearley and he is going to look into making that header the full width of the page and/or a bit smaller.

**Comment by jonearley** [comment]
@justcolin I've fixed the go button and reduced made the email size smaller to prevent wrapping. This

**Comment by jonearley** [comment]
@justcolin this pull request is ready for your review!

**Comment by justcolin** [comment]
@grosscol: This looks good to pull and then we can close #311

**Pull request merged**
