### PR TITLE
Umrdr 727 remove access link

### PR DESCRIPTION
**Pull request by jimeng**
This pull request adds two partials to override partials used to render table rows in the "My Works" and "My Collections" pages.  The new partials are exact copies of partials in [https://github.com/samvera/hyrax/tree/1-0-stable/app/views/hyrax/my/_index_partials](https://github.com/samvera/hyrax/tree/1-0-stable/app/views/hyrax/my/_index_partials) except that instead of calling the [AbilityHelper](https://github.com/samvera/hyrax/blob/1-0-stable/app/helpers/hyrax/ability_helper.rb)'s render_visibility_link method, they simply render the appropriate visibility badge.

### CODE REVIEW

**Comment by jimeng** [comment]
This still seems like the wrong fix for this bug.  The current views in Hyrax call the AbilityHelper's render_visibility_link method, which renders a link to edit all of the attributes for a document (either a work or a collection).  It seems like a "visibility link" should take the user to information about the visibility of the referenced document, rather than to a form to edit all attributes about the document. Maybe a better fix would be to override the render_visibility_link method and fix the path associated with the link.

**Comment by njaffer** [comment]
can you please add screenshots of how it looks. Adding so much code might bring extra things that we removed earlier

**Comment by jimeng** [comment]
I will delete this pull request and make a new pull request for another approach that is much more limited.

**Comment by jimeng** [comment]
Replacing this pull request with a pull request that uses a different approach

**Pull request closed without merging**
