### PR TITLE
remove ability to edit or delete work if doi is minted.

### LINKED ISSUE #482: Disable edit and delete this work if DOI is created
## Background or Context

If DOI is minted, disable: 
edit this work 
delete this work

### PR DESCRIPTION
**Pull request by blancoj**
Fixes #482

### CODE REVIEW

**Comment by billdueber** [comment]
I'm not sure I'm comfortable with disappearing buttons; the user will have no way to know why the buttons which had been present are now gone. How about we try to standardize on disabled buttons with informational text directly below them. Thoughts, anyone?

**Comment by blancoj** [comment]
how about this?

screen shot 2016-11-28 at 4 04 54 pm

**Comment by botimer** [comment]
I'm not sure about anybody else, but this "mint"/"minted" terminology seems really awkward. I get it in terms of technology and analogy, but I think we should probably use phrases like "this work has been assigned a DOI" -- it frames it in terms of the status of the work, rather than the mechanics of the identifier.

**Comment by botimer** [comment]
Also, I think a little panel/alert/message is more usable and stable in design terms than appending status info to a label in a now-disabled button.

I defer on whether the buttons should be removed or disabled, but these are not like items in a toolbar, where having them come and go will disrupt other actions. It doesn't offend me to see a message *instead* of buttons in this kind of case.

**Comment by blancoj** [comment]
here it is 


image

**Pull request merged**
