### PR TITLE
Update Sufia and Dependencies

### PR DESCRIPTION
**Pull request by njaffer**
WIP - Updated the dependencies and made some changes in the config file. I will have to re-write the method for sending the email as generic_works_url is not a method any more. 

@grosscol , @respinos: When I create a new work, I get the error: 'Un processable entity', possibly from this line: https://github.com/projecthydra-labs/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/curation_concern_controller.rb#L50

### CODE REVIEW

**Comment by njaffer** [comment]
@respinos: It seems like there is some conflict with work_form override

**Comment by respinos** [comment]
Looks like we're going to be forced to refactor the code we copied from the earlier sufia/curation_concerns releases.

**Comment by grosscol** [comment]
There are some underlying model changes that we'll have to refactor to accommodate.  Off the top of my head, I think the removal of ordered_members is going to be the most significant.  

With the finalized Sufia 7.0 UI, we'll likely have to take a look at every view we inherit.  It looks like there's going to be a lot of changes that we'll be inheriting which might not play nice.

**Comment by njaffer** [comment]
@grosscol: This should be good to go now. I have tested it by adding a work, editing a work, searching on a work and collection

**Comment by njaffer** [comment]
closes #295

**Pull request merged**
