### PR TITLE
"Add another..." multifield

### PR DESCRIPTION
**Pull request by jonearley**
This is an update to the multifield add/remove UI functionality in response to @bnhowell's work user testing this specific interaction and how the add/remove model has consistently confused users.

**Before:**

screen shot 2016-04-29 at 11 25 55 am

**After:**

screen shot 2016-04-29 at 11 25 34 am

### CODE REVIEW

**Comment by justcolin** [comment]
@jonearley: What happens to keyboard focus when a field is removed? We have to make sure it goes somewhere that makes sense instead of being lost.

Other than that, this looks good enough.

**Comment by grosscol** [comment]
@justcolin Is this good to go now?  focus issue resolved?

**Comment by justcolin** [comment]
@grosscol: There are still unresolved things. Once we resolve the focus issues you will be okay merging this request?

**Comment by grosscol** [comment]
@justcolin Yes.  As soon as you resolve the focus issue, you can merge it or ping me and I'll get to it.

**Comment by justcolin** [comment]
@grosscol Would you be okay if we delay this fix? After talking with @jonearley and @bnhowell there are a couple other things we would like to change, and we would like to first pushes those changes in Sufia/CC.

**Comment by grosscol** [comment]
Sure.  I'm fine with pushing this upstream.

**Comment by jonearley** [comment]
https://github.com/projecthydra/hydra-editor/pull/113

This idea has been merged into hydra-editor.

**Pull request closed without merging**
