### PR TITLE
WORK IN PROGRESS for PROVENANCE LOGGING - FOR REVIEW

### PR DESCRIPTION
**Pull request by gordonleacock**
See: Create provenance log to track changes Issue #639

I need some help defining what should be logged (the content).

Bill D. suggested having highly formatted logs. I don't know how to do that.

### CODE REVIEW

**Comment by jimeng** [comment]
There are gems to support structured logging.  One of them might be a starting point. 

Since I will be working on a viewer for the provenance log, I would propose some ideas about possible approaches to support filtering and sorting.  Basically think of GREP as a way to extract information from a log.  Start with timestamps.  They are well structured.  If each line of a log starts with a timestamp, it's easy to write a RegEx that matches all log entries within a specific time period.  It's not as simple as dealing with datetime objects, but it is pretty straightforward.  

Suppose each log entry references a specific Work (not necessarily true, but just suppose).  So maybe each log entry starts with a 20-character timestamp followed by a space and a positive integer representing the ID of the Work followed by a space.  We can then write a RegEx to select all log entries related to that Work.  The key might be using delimiters to separate and identify different fields.  If every log entry has the same "fields" (e.g. work_id, user_id, action_type) we can use delimiters and position alone.  If some entries have work_id and others have admin_set_id or something else, we might use delimiters that identify the meaning of the data that follows.  If all values for a "field" have the same length (as in the parts of timestamps), position within the string may be sufficient.  

I can imagine simple ways to create a log writer, but I'd guess that whatever I can imagine has already been done and turned into a gem that does it better.

**Comment by jimeng** [comment]
The log could be a series of simple text entries in which each entry starts with a timestamp and other structured data fields followed by a human-readable text message.  The human readable message may be extraneous if it just contains the same information that is in the structured fields, but it is worthwhile if it adds important details about the event that is being logged. 

Simple text is the most common way to structure a log, but it appears that some people also use JSON or XML to provide the structure.

**Comment by jimeng** [comment]
I went looking for ruby gems that support structured logging.  By far the most downloaded gem in this category is the [cabin gem](https://rubygems.org/gems/cabin).

**Comment by billdueber** [comment]
For structured logging, there's also [semantic logger](https://rocketjob.github.io/semantic_logger/rails.html), but I think we should probably 
look at the [logstash format](https://github.com/dwbutler/logstash-logger). A&E is already working on a logstash installation for local use.

Default output looks something like this:

```json
# Call is: logger.info "test"
{  
   "message":"test",
   "@timestamp":"2014-05-22T09:37:19.204-07:00",
   "@version":"1",
   "severity":"INFO",
   "host":"[hostname]"
}

# Call is: logger.debug message: 'test', foo: 'bar'
{  
   "message":"test",
   "foo":"bar",
   "@timestamp":"2014-05-22T09:43:24.004-07:00",
   "@version":"1",
   "severity":"DEBUG",
   "host":"[hostname]"
}
```

**Comment by jimeng** [comment]
Does logstash require more than just adding the gem and some configuration?  It looks good to me.  We will want to rely more on the values of a limited set of attributes describing the event, rather than the human -readable message.

**Pull request closed without merging**
